# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Portfolio
    local_business_type: ""
    org_name: ""
    description: "The website is created using Hugo Academic theme powered by Hugo Blox Builder. It is a simple and elegant theme for academic websites."
    twitter: "annu92921509"
  analytics:
    google_analytics: ""
    baidu_tongji: ""
    plausible: ""
    fathom: ""
    pirsch: ""
  verification:
    google: ""
    baidu: ""

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Ananya Vivek Kulkarni"

# Site footer
footer:
  copyright:
    notice: "© 2024 Ananya Vivek Kulkarni. This work is licensed under MIT License."
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
