# Site settings
title: "Ananya Kulkarni's Academic Website"
email: "ananyakulkarni2103@gmail.com"
description: "Showcasing my research, projects, and academic work."
baseurl: ""
url: "https://ananya12k.github.io"
avatar: "/images/profile.jpg"
remote_theme: "mmistakes/minimal-mistakes"

# Social media links
social_links:
  - {
      name: "Email",
      link: "mailto:ananyakulkarni2103@gmail.com",
      icon: "fas fa-envelope",
    }
  - {
      name: "LinkedIn",
      link: "https://linkedin.com/in/ananya-kulkarni-609213244",
      icon: "fab fa-linkedin",
    }
  - {
      name: "GitHub",
      link: "https://github.com/ananya12k",
      icon: "fab fa-github",
    }
  - {
      name: "Google Scholar",
      link: "https://scholar.google.com/citations?user=GddubbUAAAAJ",
      icon: "fas fa-graduation-cap",
    }

# Navbar configuration
navbar:
  - { name: "Home", link: "/" }
  - { name: "About", link: "/about" }
  - { name: "Blog", link: "/blog" }
  - { name: "Projects", link: "/projects" }
  - { name: "Publications", link: "/publications" }
  - { name: "Bio", link: "/bio" }
  - { name: "Search", link: "/search" }

# Collections configuration
collections:
  about:
    output: true
  blog:
    output: true
  projects:
    output: true
  publications:
    output: true
  bio:
    output: true

# Pagination settings
paginate: 5
paginate_path: "/page:num/"
